### ISSUE TITLE
Able to get raidfinder running but then it stops after a second

### ISSUE THREAD

**Issue by Rimewind** [Frizz925/gbf-simple-raidfinder#2]
Hey, thanks for writing the readme, it really helped me out.  I actually am able to get it running, but then after maybe around a second it bugs out.  I copied and pasted what it gave me below.  Appreciate it a lot, trying my best to figure it out.

[15:55:26] Starting stream...
[15:55:26] Connected.
[15:55:28] Found new raid:
[Boss] 0FCADC7A (Lvl 75 Luminiera Omega)
[From] RaspberryGBF (Yggdrasil Lover)
[Message]
[Action] Copied to clipboard
[15:55:28] Found new raid:
[Boss] 1CDA2A94 (Lvl 75 Luminiera Omega)
[From] ParamitsuRyuZu (YayaRyuzu)
[Message]
[Action] Copied to clipboard
Traceback (most recent call last):
  File "main.py", line 147, in main
    stream.filter(track=listener.streamFilter)
  File "C:\Users\Fabella\AppData\Local\Programs\Python\Python35\lib\site-packages\tweepy\streaming.py", line 445, in filter
    self._start(async)
  File "C:\Users\Fabella\AppData\Local\Programs\Python\Python35\lib\site-packages\tweepy\streaming.py", line 361, in _start
    self._run()
  File "C:\Users\Fabella\AppData\Local\Programs\Python\Python35\lib\site-packages\tweepy\streaming.py", line 294, in _run
    raise exception
  File "C:\Users\Fabella\AppData\Local\Programs\Python\Python35\lib\site-packages\tweepy\streaming.py", line 263, in _run
    self._read_loop(resp)
  File "C:\Users\Fabella\AppData\Local\Programs\Python\Python35\lib\site-packages\tweepy\streaming.py", line 324, in _read_loop
    self._data(next_status_obj)
  File "C:\Users\Fabella\AppData\Local\Programs\Python\Python35\lib\site-packages\tweepy\streaming.py", line 297, in _data
    if self.listener.on_data(data) is False:
  File "C:\Users\Fabella\AppData\Local\Programs\Python\Python35\lib\site-packages\tweepy\streaming.py", line 54, in on_data
    if self.on_status(status) is False:
  File "main.py", line 106, in on_status
    self.handleTweet(parsed)
  File "main.py", line 95, in handleTweet
    logMessage(message)
  File "main.py", line 35, in logMessage
    message = message.encode().decode(sys.stdout.encoding)
UnicodeDecodeError: 'cp932' codec can't decode byte 0x8a in position 78: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 156, in <module>
    main()
  File "main.py", line 151, in main
    traceback.print_exc(e)
  File "C:\Users\Fabella\AppData\Local\Programs\Python\Python35\lib\traceback.py", line 159, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Users\Fabella\AppData\Local\Programs\Python\Python35\lib\traceback.py", line 100, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "C:\Users\Fabella\AppData\Local\Programs\Python\Python35\lib\traceback.py", line 464, in __init__
    capture_locals=capture_locals)
  File "C:\Users\Fabella\AppData\Local\Programs\Python\Python35\lib\traceback.py", line 322, in extract
    if limit >= 0:
TypeError: unorderable types: UnicodeDecodeError() >= int()

**Comment by frizz925** [comment]
This is a bug caused by Python and Windows' CMD when the raidfinder is printing out unicode characters obtained from the tweets. I've added a new option in the configuration to make the raidfinder only print the raid codes, avoiding any unwanted unicode characters to be printed out. Pull the newest commit and add this option to your *config.ini*

```ini
[Raidfinder]
...
OnlyPrintCodes = yes
```

**Comment by Rimewind** [comment]
Hey, that fixed it, it works now.  Thank's so much
